### ISSUE TITLE
samsung A52016 not compatible

### ISSUE THREAD

**Issue by timFaivre** [NordicSemiconductor/Android-Nordic-Thingy#1]
More to let you know that the current store release (v1.1.7) seems  not compatible with the samsung A5-2016  as the Thingy keeps disconnecting all the time.

**Comment by roshanrajaratnam** [comment]
Hi thanks for reporting the issue. Could you try increasing the maximum connection interval to see if it helps for example something like 80 units? Could you also provide the device details?

**Comment by timFaivre** [comment]
device : galaxy A5 2016 (SM-A510F)  running android 6.0.1 (kernel 3.10.61) 
I'm not sure if you need more info... 
increasing the connection interval (using a samsumg S4 which seems working, altough not in your list) does not help. 

update : strange things is that it is working fine through web based interface !

**Comment by E3V3A** [comment]
Is this still an issue?
Without an actually error message or reproductive log, I think its time to close this.

**Comment by timFaivre** [comment]
yes you can close, (I was not instructed any procedure to feed more logs, and not able to produce more of them by myself, too bad).

**Comment by roshanrajaratnam** [comment]
@timFaivre we also believe this is specifically an Android device related issue as we have noticed this happenning on certain samsung devices. May be we can blame it on the Android fragmentation and ble chipset. Sorry if this thread hasn't been of much help!

**Comment by E3V3A** [comment]
Yeah, I hear you. It may have been a permission or FW problem.

AOS 6 introduced the new permission system and Samsung was notoriously known to miss a lot of things and mess up the permissions including SELinux (Aka SEAndroid) extensions on many of their non-top end phones, while refusing to provide OS updates. 
...and now we are facing the new permission system in Q...starting all over again. :nauseated_face:
