### ISSUE TITLE
Is there a typo in the FOREGROUND_SERVICE permission?

### ISSUE THREAD

**Issue by E3V3A** [NordicSemiconductor/Android-Nordic-Thingy#14]
It look as though there is a typo [here](https://github.com/NordicSemiconductor/Android-Nordic-Thingy/blob/master/app/src/main/AndroidManifest.xml#L49).
Or is that something new and specific for `O`?

**Comment by roshanrajaratnam** [comment]
@E3V3A It certainly seems like a typo. Funny enough it still seems to work even with a typo! Nice catch and thanks for reporting this.

**Comment by E3V3A** [comment]
You're welcome. I really enjoy this device and I'm very happy someone is taking the bother to keep this up-to-date. With so many changes in Android in the last year or so, it's crazy to try to keep things up. 

I see you just fixed it, so closing this.
