### ISSUE TITLE
Mistake in ThingyListenerHelper.java

### ISSUE THREAD

**Issue by robertkowalewski** [NordicSemiconductor/Android-Nordic-Thingy#17]
The lines 258-259 are the following:
```
final float compassY = intent.getExtras().getFloat(ThingyUtils.EXTRA_DATA_GYROSCOPE_Y);
final float compassZ = intent.getExtras().getFloat(ThingyUtils.EXTRA_DATA_GYROSCOPE_Z);
```
Is it correct? I think that arguments for these functions should be EXTRA_DATA_COMPASS_Y and EXTRA_DATA_COMPASS_Z (instead these arguments which are present currently).

**Comment by roshanrajaratnam** [comment]
@Rik93, nice catch! Will fix it soon
