### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by kryzysoft** [NordicSemiconductor/Android-Nordic-Thingy#2]
Hello. I wanted to check temperature in my freezer using Thingy. I put it inside and wait few minutes for cooling it down and tried to read the temperature on my phone. It was about 250 degree! Probably you have to change the file 
 Android-Nordic-Thingy/thingylib/src/main/java/no/nordicsemi/android/thingylib/ThingyConnection.java
on line 339:
final int mTemperatureInt = characteristic.getIntValue(BluetoothGattCharacteristic.**FORMAT_UINT8**, 0);
to
final int mTemperatureInt = characteristic.getIntValue(BluetoothGattCharacteristic.**FORMAT_SINT8**, 0);
I didn't tested it but i think it will work.

**Comment by philips77** [comment]
We in Norway should know that temperature may be below zero.. ;)

**Comment by roshanrajaratnam** [comment]
@kryzysoft nice catch. According to the thingy spec yes it is an FORMAT_SINT8 ;)
