### ISSUE TITLE
Nordic Thingy:52 Error 8 GATT connection

### ISSUE THREAD

**Issue by Xiryl** [NordicSemiconductor/Android-Nordic-Thingy#22]
I'm creating an android app that wants to save all the values from the nordic thingy 52.

Inside my `ThingyListener`, I implement all the avilable methos to store the received values for each notification type

e.g.
```java
private ThingyListener mThingyListener = new ThingyListener() {
 // [...] other override methods
 @Override
        public void onTemperatureValueChangedEvent(BluetoothDevice bluetoothDevice, String temperature) {
            // do stuff
        }
 // [...] other override methods
@Override
        public void onQuaternionValueChangedEvent(BluetoothDevice bluetoothDevice, float w, float x, float y, float z) {
            // do stuff
        }
 // [...] other override methods
}
```

When i connect the `BluetoothDevice` to the `ThingyListener`, I enable all the Notifications available from the `ThingySdkManager`:
```java
            thingySdkManager.enableBatteryLevelNotifications(device, true);
            thingySdkManager.enableButtonStateNotification(device, true);
            thingySdkManager.enableColorNotifications(device, true);
            thingySdkManager.enableEnvironmentNotifications(device, true);
            thingySdkManager.enableEulerNotifications(device, true);
            thingySdkManager.enableGravityVectorNotifications(device, true);
            thingySdkManager.enableHeadingNotifications(device, true);
            thingySdkManager.enableHumidityNotifications(device, true);
            thingySdkManager.enableOrientationNotifications(device, true);
            thingySdkManager.enablePedometerNotifications(device, true);
            thingySdkManager.enablePressureNotifications(device, true);
            thingySdkManager.enableQuaternionNotifications(device, true);
            thingySdkManager.enableRawDataNotifications(device, true);
            thingySdkManager.enableRotationMatrixNotifications(device, true);
            thingySdkManager.enableSoundNotifications(device, true);
            thingySdkManager.enableSpeakerStatusNotifications(device, true);
            thingySdkManager.enableTapNotifications(device, true);
            thingySdkManager.enableThingyMicrophone(device, true);
            thingySdkManager.enableUiNotifications(device, true);
            ThingyListenerHelper.registerThingyListener(getApplicationContext(), mThingyListener, device);
```

I also see that I can change the frequency of some notification, such as 
```java
thingySdkManager.setMotionProcessingFrequency(device, 200);
```

My problem is, if I don't set the `motionfrequency`, the sampling goes perfectly. As soon as I set the requency from a range between 5 to 200, the nordic disconnects with Bluetooth GATT 8 error.

```log
2020-04-02 13:00:16.607 15336-15396/it.chiarani.beacon_detection D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=9 device=F5:EF:EE:8B:92:7C
2020-04-02 13:00:16.609 15336-15380/it.chiarani.beacon_detection D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=11 device=F5:EF:EE:8B:92:7C
2020-04-02 13:00:16.609 15336-15654/it.chiarani.beacon_detection D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=10 device=F5:EF:EE:8B:92:7C
2020-04-02 13:00:16.610 15336-15654/it.chiarani.beacon_detection V/ThingyConnection: Error 8 : F5:EF:EE:8B:92:7C
2020-04-02 13:00:16.611 15336-15654/it.chiarani.beacon_detection D/BluetoothGatt: close()
2020-04-02 13:00:16.611 15336-15654/it.chiarani.beacon_detection D/BluetoothGatt: unregisterApp() - mClientIf=10
2020-04-02 13:00:16.670 15336-15336/it.chiarani.beacon_detection V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
```

The only configuration that I found that works is:
```java
thingySdkManager.enableMotionNotifications(device, true);
thingySdkManager.setMotionProcessingFrequency(device, 200);
ThingyListenerHelper.registerThingyListener(getApplicationContext(), mThingyListener, device);
```

From this configuration, if I enable `enableTemperatureNotifications` or others Notification (I also try to change `setAdvertisingIntervalUnits` or `setTemperatureInterval`) the device disconnect itself.

How can I solve the problem, by keeping all notifications active and still setting a frequency without experiencing GATT disconnection?

**Comment by roshanrajaratnam** [comment]
@Xiryl Motion frequency takes up a lot of bandwidth so I guess you have to find out what's the most optimized frequency I guess. This could be the reason why it disconnects when you increase the frequency of all of it.

**Comment by Xiryl** [comment]
The strange thing is that by activating only the motion notifications group I can set the minimum and maximum frequency without any problem

e.g.
```java
thingySdkManager.enableMotionNotifications(device, true);
thingySdkManager.setMotionProcessingFrequency(device, FREQ_HZ);
// FREQ_HZ range is 5-200
```

but as soon as I enable another type of notification, such as the temperature, the connection crash.

You said it could be a bandwidth problem, but my tests shows that I can't use/specify `setMotionProcessingFrequency` with other events than those of the `MotionNotification` group.
Instead, without specifying the frequency with `setMotionProcessingFrequency`, it is possible to activate all the notification events without having connection and/or bandwidth problems

Is this a Nordic firmware bug or a sdk bug?

**Comment by roshanrajaratnam** [comment]
@Xiryl yes `setMotionProcessingFrequency`  is only applicable to the frequency of the motion sensors. What I meant is enabling all notifications for all sensors could cause bandwidth issues, connection drop out or you might loose certain notifications. However the issue you are talking about seems like an issue on the firmware side. Is this something you can reproduce with the sample app as well?

**Comment by Xiryl** [comment]
Yes, I tried from the official application "Nordic Thingy" (downloaded from the playstore) and if I set the frequencies (from left menu -> configuration -> advanced), and then from the side menu I open the "motion" section the nordic disconnects.
