### ISSUE TITLE
Nordic BluetoothGatt status 8

### ISSUE THREAD

**Issue by hubeen** [NordicSemiconductor/Android-Nordic-Thingy#27]
i'm creating an android app that want to battry value, pressure value, micro pcm data from nordic thingy 52.

I tried enable Notifications.

```
mDatabaseHelper.updateNotificationsState(mDevice.getAddress(), true, ThingyDbColumns.COLUMN_NOTIFICATION_PRESSURE);
mThingySdkManager.enablePressureNotifications(mDevice, true);
mThingySdkManager.enableBatteryLevelNotifications(mDevice, true);
mThingySdkManager.setMaximumConnectionIntervalUnits(mDevice, 96);
mThingySdkManager.enableSoundNotifications(mDevice, true);
mThingySdkManager.requestMtu(mDevice);
mThingySdkManager.enableSpeakerStatusNotifications(mDevice,true);
```

only get battry, pressure than it's okay
but i'm tried that code

`mThingySdkManager.enableThingyMicrophone(mDevice, true);`

but it's nor working.
```
D/BluetoothGatt: setCharacteristicNotification() - uuid: ef680504-9b35-4933-9b10-52ffa9740042 enable: true
W/AudioTrack: releaseBuffer() track 0x7c8cc3f400 disabled due to previous underrun, restarting
D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=6 device=D1:EE:3C:5C:37:9B
V/ThingyConnection: Error 8 : D1:EE:3C:5C:37:9B
D/BluetoothGatt: close()
D/BluetoothGatt: unregisterApp() - mClientIf=6
```
my problem is, if i dont set the `enableThingyMicrophone`,  the sampling goes perfectly
How can I solve the problem?

I'm sorry for my bad English.

[+] The same connection error occurs when you use the microphone only in the official app.

**Comment by Xiryl** [comment]
A similar problem happens to me. See issue #22 

The fact is that you can't activate or enable tot sensors at once, otherwise the connection crashes. Tested it on the official app as well and notified, but never got a response :)
