### ISSUE TITLE
Android App Thingy:52 incompatible with latest Andoid OS

### ISSUE THREAD

**Issue by eabase** [NordicSemiconductor/Android-Nordic-Thingy#31]
A recompilation and update is needed for this app. 

It's been a real fun app to use, but as we have to upgrade our old phones at least every 2 years, this app is no longer compatible with the latest Android OS. 

Please consider to make KTLO update. 

Thanks. 

Refs:
* https://play.google.com/store/apps/details?id=no.nordicsemi.android.nrfthingy
* email:android-devs@nordicsemi.no

**Comment by roshanrajaratnam** [comment]
Hei @eabase will take a look at this.

**Comment by eabase** [comment]
@roshanrajaratnam 
Did you have a look? 

In addition, it may be a great idea to:
- Remove all outdated Android API compatibilities lower than **10**. (Less [than](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) 5% of worldwide Android are using APIs below 9. And I'm pretty sure they are not nRF developers!)
- also make this compatible with `Thingy:91`.

**Comment by roshanrajaratnam** [comment]
@eabase I am looking in to this as we speak. I am quite busy with some other priorities. We gladly accept pull requests as well :)

Unfortunately we will not be adding support to Thingy:91 on this.

**Comment by eabase** [comment]
@roshanrajaratnam 

> I am looking in to this as we speak.

Thank you. That's all we can ask. 

> We gladly accept pull requests as well

Don't we all! :D

But in this case we can't even install it, and much less run it, so any PR's or mods are currently out of the question.  In addition we are looking at developing other things for this device, to support our customers, that would in the end benefit Nordic.  So functional maintenance of *your* Demo products should really be of high business interest on Nordic's side. 

> Unfortunately we will not be adding support to Thingy:91 on this.

That's too bad, because the 91 is a really cool device, with most of the sensors and HW already the same as in the 52. Do you have any idea how much effort in terms of SW components/libs would be necessary to create a similar app (once the 52 is back to shape.)?

**Comment by roshanrajaratnam** [comment]
@eabase 

> That's too bad, because the 91 is a really cool device, with most of the sensors and HW already the same as in the 52. Do you have any idea how much effort in terms of SW components/libs would be necessary to create a similar app (once the 52 is back to shape.)?

Well if you are referring to building a similar app for a 52 device, I would say at least 3 months or so. Regarding the current update, I will push a version with a KTLO update that should get you going. Unfortunately I am assigned with other high priority tasks. Keep an eye on #32.

**Comment by roshanrajaratnam** [comment]
HI @eabase I've just pushed v1.4.4 of the app. Hope this helps you going ahead with your product development.
 https://github.com/NordicSemiconductor/Android-Nordic-Thingy/releases/latest

**Comment by eabase** [comment]
@roshanrajaratnam 
I have now tried the app on different phones and it crashes every time... 🛑 
Did you actually test it? (How?)

**Comment by roshanrajaratnam** [comment]
Of course, it was tested on a pixel 5 and a pixel 6.

Where exactly is it crashing? Could you provide some more details?

**Comment by eabase** [comment]
> Of course, it was tested on a pixel 5 and a pixel 6.

🤣 As always... any magic that works on Pixels, are very unlikely to work anywhere else. 

> Where exactly is it crashing? 

Just after the Thingy splash screen, when you click the `Continue` button.

**Comment by eabase** [comment]
@roshanrajaratnam 
**It works now.**  🎉 

The bug is that if you don't *already* have BT enabled when you start the app the **first time**, it just crashes after hitting the `[Continue]` button, so it never reaches the part where you need to grant the 3 BT related permissions. (So that it can turn on BT itself upon startup.)

I found out when on one of the devices (not the other) I found a nag thing in the drop down tray, asking me to enable BT. Funny enough it was not possible on that device to clear the nag in the system tray. So I accepted and then found out that the app worked and started asking me to grant all the required permissions. 

---

**FW bugs**

My Thingy:52 was one of the first devices shipped. So the app asked me to update the FW from `2.1.0` to `2.2.0`. 
After I did that the Sound got really terrible and only the piano plays correctly. 

1. In the "PCM" tab, the `*.wav` files plays, but once done, leaves a terrible noise on. 
2. In the button "Samples" tab. Same thing for the button noises. After the laser beam, the noise is really loud.
 
**NOTE**: This doesn't happen immediately, but only after a while...

3. The compass is completely off and keep drifting in a very strange way...
4. if I move the device rapidly, then the compass shows a completely different direction.  

I've never seen anything like this. Maybe the Hall sensor got messed up by something? 
Do you know anything about that? (Maybe sensitive to heat or get broken by strong external magnets?)

**Comment by roshanrajaratnam** [comment]
@eabase thanks for the detailed report. I have done a fix for this and have uploaded a version to play store as we speak.

Some of the FW bugs are known issues due to device fragmentation and BLE controller related performance that may vary from device to device. You can do try a combination of the following to see if it helps

1. Disable all other notifications i.e. weather and motion notifications.
2. Reduce the connection interval time. If I'm not mistaken, newer Android versions do service discovery at 7.5ms and switch to 11ms connection interval. You could configure this on the Thingy Configuration screen and see if it improves. The audio stream just uses notifications 

Compass has been a bit off due to the placement of battery If I recall correctly.

Unfortunately there is not much I can do related to the FW stuff as it is out of my scope and there is no more activity on the firmware side of things.  You could also create a ticket on DevZone to see if you could get more help on the fw related issues.

**Comment by eabase** [comment]
@roshanrajaratnam

Thanks a lot Roshan, for helping and fixing it this quickly.

**Comment by eabase** [comment]
In case someone else get's here: 

Check this out: 
https://github.com/NordicSemiconductor/Nordic-Thingy52-FW/issues/29#issuecomment-404522892
https://devzone.nordicsemi.com/f/nordic-q-a/36351/3d-motion-problem-in-a-specified-movement/147347
