### ISSUE TITLE
Samsung A5 2017 with Nougat - Non-compatible

### ISSUE THREAD

**Issue by Jaden-J** [NordicSemiconductor/Android-Nordic-Thingy#4]
Hi,

I've couple of Nordic Thingy 52.
I was able to connect to these using my Samsung A5 2017 running Marshmallow and see the various sensor readings.

After an OS update on Samsung A5 2017 from Marshmallow to Nougat, I'm able to see the Thingys but unable to connect. I tried connecting with the earlier Android app (which used to connect pre-OS update) and also an updated Nordic Thingy Android app after the OS update; but enable to establish connection.

I installed the Nordic Thingy app on a colleague's Samsung S8 running Nougat and its able to see and connect to Thingys.

Is there a matrix of Phone/OS App version compatibility. Is there a known issue with Samsung A5 2017 with Nougat.

Is there a workaround to get Thingy working on Samsung A5 2017.

Thanks in advance for any helpful suggestions.

- DJ

===========================
Non Working:
===========================
Device : Samsung A5 2017
OS: Nougat
Nordic Thingy App version: 1.3.2

===========================
Working:
===========================
Device : Samsung A5 2017
OS: Marshmallow
Nordic Thingy App version: pre 1.3.2

Device : Samsung Galaxy S8
OS: Nougat
Nordic Thingy App version: 1.3.2

**Comment by E3V3A** [comment]
Is this still an issue?
Without an actually error message or reproductive log, I think its time to close this.
