### ISSUE TITLE
Thingy reports LED color incorrectly

### ISSUE THREAD

**Issue by philips77** [NordicSemiconductor/Android-Nordic-Thingy#6]
I set up the LED color on a Thingy to Constant #FF0000. It glows red as expected. Then I click DISCONNECT and CONNECT again. The app shows inverted colors as shown below:
![thuingy_bug_led](https://user-images.githubusercontent.com/6576580/32374505-5993404e-c09e-11e7-85cb-93651d026901.png)

**Comment by roshanrajaratnam** [comment]
Thanks for reporting this issue. This has been fixed in the latest release v1.3.4
